external: curlpp: update to current master
This fixes a build issue with newer `libcurl` versions

```
viewtouch/external/curlpp/include/curlpp/Options.hpp:281:74: error: invalid conversion from ‘int’ to ‘CURLoption’ [-fpermissive]
  281 |         typedef curlpp::OptionTrait<curl_closepolicy, CURLOPT_CLOSEPOLICY> ClosePolicy;
      |                                                                          ^
      |                                                                          |
      |                                                                          int
```

https://github.com/jpbarrette/curlpp/commit/d080e301ec71061c46049d23fedfb8106be3153f

Cleanup checked in `libcurl` files by removing files like examples and
tests, not needed to build ViewTouch.

Fixes: https://github.com/ViewTouch/viewtouch/issues/157